CREATE TABLE tb_channel
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    author_id   BIGINT,
    CONSTRAINT pk_tb_channel PRIMARY KEY (id)
);