CREATE TABLE posts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    text       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    author_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE users_posts
(
    user_id  BIGINT NOT NULL,
    posts_id BIGINT NOT NULL
);

ALTER TABLE users_posts
    ADD CONSTRAINT uc_users_posts_posts UNIQUE (posts_id);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE users_posts
    ADD CONSTRAINT fk_usepos_on_post FOREIGN KEY (posts_id) REFERENCES posts (id);

ALTER TABLE users_posts
    ADD CONSTRAINT fk_usepos_on_user FOREIGN KEY (user_id) REFERENCES users (id);